-- CreateTable
CREATE TABLE "Config" (
    "id" SERIAL NOT NULL,
    "tenantId" INTEGER NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "mobile" TEXT,
    "address" TEXT,
    "googlemap" TEXT,
    "facebook" TEXT,
    "zalo" TEXT,
    "instagram" TEXT,
    "tiktok" TEXT,
    "youtube" TEXT,
    "x" TEXT,
    "linkedin" TEXT,
    "logo" TEXT,
    "banner" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "showAddress" BOOLEAN NOT NULL DEFAULT true,
    "showEmail" BOOLEAN NOT NULL DEFAULT true,
    "showFacebook" BOOLEAN NOT NULL DEFAULT true,
    "showGooglemap" BOOLEAN NOT NULL DEFAULT false,
    "showInstagram" BOOLEAN NOT NULL DEFAULT false,
    "showLinkedin" BOOLEAN NOT NULL DEFAULT false,
    "showMobile" BOOLEAN NOT NULL DEFAULT true,
    "showTiktok" BOOLEAN NOT NULL DEFAULT false,
    "showX" BOOLEAN NOT NULL DEFAULT false,
    "showYoutube" BOOLEAN NOT NULL DEFAULT false,
    "showZalo" BOOLEAN NOT NULL DEFAULT false,
    "VNP_TMN_CODE" TEXT,
    "VNP_SECRET" TEXT,
    "VNP_API_URL" TEXT,
    "EMAIL_USER" TEXT,
    "EMAIL_PASS" TEXT,
    "EMAIL_FROM" TEXT,

    CONSTRAINT "Config_pkey" PRIMARY KEY ("id")
);
